// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxsQL9l9tkKAlx0aCFMiySjzFVbyLM9KI',
    appId: '1:558705895015:web:5a960a543eafc25b0c56c2',
    messagingSenderId: '558705895015',
    projectId: 'easy-life-test-3a81c',
    authDomain: 'easy-life-test-3a81c.firebaseapp.com',
    storageBucket: 'easy-life-test-3a81c.appspot.com',
    measurementId: 'G-3LM431TREX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi0cNzm0qSoZQvksKgFHJzoQ3frysh1DY',
    appId: '1:558705895015:android:63040b5046dbbe400c56c2',
    messagingSenderId: '558705895015',
    projectId: 'easy-life-test-3a81c',
    storageBucket: 'easy-life-test-3a81c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByclyO9aj9HWDJ4Uo3hu-tJmoK_YuXGqA',
    appId: '1:558705895015:ios:e0fab526ab3f051f0c56c2',
    messagingSenderId: '558705895015',
    projectId: 'easy-life-test-3a81c',
    storageBucket: 'easy-life-test-3a81c.appspot.com',
    iosBundleId: 'com.easy-life.easy-life-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByclyO9aj9HWDJ4Uo3hu-tJmoK_YuXGqA',
    appId: '1:558705895015:ios:e0fab526ab3f051f0c56c2',
    messagingSenderId: '558705895015',
    projectId: 'easy-life-test-3a81c',
    storageBucket: 'easy-life-test-3a81c.appspot.com',
    iosBundleId: 'com.easy-life.easy-life-app',
  );

}